import {
  Attribute,
  Skill,
  Augmentation,
  LuminanceAura,
  NumberIndexedDict
 } from "./types";

export const ATTRIBUTE_NAME = {
  [Attribute.strength]: "Strength",
  [Attribute.endurance]: "Endurance",
  [Attribute.coordination]: "Coordination",
  [Attribute.quickness]: "Quickness",
  [Attribute.focus]: "Focus",
  [Attribute.self]: "Self",
}

export const SKILL_NAME = {
  [Skill.alchemy]: "Alchemy",
  [Skill.arcane_lore]: "Arcane Lore",
  [Skill.armor_tinkering]: "Armor Tinkering",
  [Skill.assess_creature]: "Assess Creature",
  [Skill.assess_person]: "Assess Person",
  [Skill.cooking]: "Cooking",
  [Skill.creature_enchantment]: "Creature Enchantment",
  [Skill.deception]: "Deception",
  [Skill.dual_wield]: "Dual Wield",
  [Skill.dirty_fighting]: "Dirty Fighting",
  [Skill.finesse_weapons]: "Finesse Weapons",
  [Skill.fletching]: "Fletching",
  [Skill.healing]: "Healing",
  [Skill.heavy_weapons]: "Heavy Weapons",
  [Skill.item_enchantment]: "Item Enchantment",
  [Skill.item_tinkering]: "Item Tinkering",
  [Skill.jump]: "Jump",
  [Skill.leadership]: "Leadership",
  [Skill.life_magic]: "Life Magic",
  [Skill.light_weapons]: "Light Weapons",
  [Skill.lockpick]: "Lockpick",
  [Skill.loyalty]: "Loyalty",
  [Skill.magic_defense]: "Magic Defense",
  [Skill.magic_item_tinkering]: "Magic Item Tinkering",
  [Skill.mana_conversion]: "Mana Conversion",
  [Skill.melee_defense]: "Melee Defense",
  [Skill.missile_defense]: "Missile Defense",
  [Skill.missile_weapons]: "Missile Weapons",
  [Skill.recklessness]: "Recklessness",
  [Skill.run]: "Run",
  [Skill.salvaging]: "Salvaging",
  [Skill.shield]: "Shield",
  [Skill.sneak_attack]: "Sneak Attack",
  [Skill.summoning]: "Summoning",
  [Skill.two_handed_combat]: "Two Handed_Combat",
  [Skill.void_magic]: "Void Magic",
  [Skill.war_magic]: "War Magic",
  [Skill.weapon_tinkering]: "Weapon Tinkering"
};

export const BUFF_NAME: NumberIndexedDict<string> = {
  0: "",
  1: "I",
  2: "II",
  3: "III",
  4: "IV",
  5: "V",
  6: "VI",
  7: "VII",
  8: "VIII"
};

export const CANTRIP_NAME: NumberIndexedDict<string> = {
  0: "None",
  1: "Minor",
  2: "Major",
  3: "Epic",
  4: "Leg."
};

export const AUGMENTATION_NAME = {
  [Augmentation.might_of_the_seventh_mule]: "Might of the Seventh Mule",
  [Augmentation.shadow_of_the_seventh_mule]: "Shadow of the Seventh Mule",
  [Augmentation.infused_war_magic]: "Infused War Magic",
  [Augmentation.infused_life_magic]: "Infused Life Magic",
  [Augmentation.infused_item_magic]: "Infused Item Magic",
  [Augmentation.infused_creature_magic]: "Infused Creature Magic",
  [Augmentation.infused_void_magic]: "Infused Void Magic",
  [Augmentation.clutch_of_the_miser]: "Clutch of the Miser",
  [Augmentation.enduring_enchantment]: "Enduring Enchantment",
  [Augmentation.quick_learner]: "Quick Learner",
  [Augmentation.asherons_lesser_benediction]: "Asherons Lesser Benediction",
  [Augmentation.asherons_benediction]: "Asherons Benediction",
  [Augmentation.blackmoors_favor]: "Blackmoor's Favor",
  [Augmentation.innate_renewal]: "Innate Renewal",
  [Augmentation.reinforcement_of_the_lugians]: "Reinforcement of the Lugians",
  [Augmentation.bleearghs_fortitude]: "Bleeargh's Fortitude",
  [Augmentation.oswalds_enhancement]: "Oswald's Enhancement",
  [Augmentation.siraluuns_blessing]: "Siraluun's Blessing",
  [Augmentation.enduring_calm]: "Enduring Calm",
  [Augmentation.steadfast_will]: "Steadfast Will",
  [Augmentation.enhancement_of_the_mace_turner]: "Enhancement of the Mace Turner",
  [Augmentation.enhancement_of_the_blade_turner]: "Enhancement of the Blade Turner",
  [Augmentation.enhancement_of_the_arrow_turner]: "Enhancement of the Arrow Turner",
  [Augmentation.storms_enhancement]: "Storm's Enhancement",
  [Augmentation.fiery_enhancement]: "Fiery Enhancement",
  [Augmentation.icy_enhancement]: "Icy Enhancement",
  [Augmentation.caustic_enhancement]: "Caustic Enhancement",
  [Augmentation.critical_protection]: "Critical Protection",
  [Augmentation.frenzy_of_the_slayer]: "Frenzy of the Slayer",
  [Augmentation.iron_skin_of_the_invincible]: "Iron Skin of the Invincible",
  [Augmentation.eye_of_the_remorseless]: "Eye of the Remorseless",
  [Augmentation.hand_of_the_remorseless]: "Hand of the Remorseless",
  [Augmentation.ciandras_fortune]: "Ciandra's Fortune",
  [Augmentation.charmed_smith]: "Charmed Smith",
  [Augmentation.jibrils_essence]: "Jibrils Essence",
  [Augmentation.yoshis_essence]: "Yoshi's Essence",
  [Augmentation.celdiseths_essence]: "Celdiseth's Essence",
  [Augmentation.kogas_essence]: "Koga's essence",
  [Augmentation.ciandras_essence]: "Ciandra's Essence",
  [Augmentation.master_of_the_steel_circle]: "Master of the Steel Circle",
  [Augmentation.master_of_the_five_fold_path]: "Master of the Five Fold Path",
  [Augmentation.master_of_the_focused_eye]: "Master of the Focused Eye",
  [Augmentation.jack_of_all_trades]: "Jack of All Trades",
  [Augmentation.archmages_endurance]: "Archmage's Endurance"
};

export const LUMINANCE_AURA_NAME = {
  [LuminanceAura.aetheric_vision]: "Aetheric Vision",
  [LuminanceAura.craftsman]: "Craftsman",
  [LuminanceAura.glory]: "Glory",
  [LuminanceAura.mana_flow]: "Mana Flow",
  [LuminanceAura.mana_infusion]: "Mana Infusion",
  [LuminanceAura.protection]: "Protection",
  [LuminanceAura.purity]: "Purity",
  [LuminanceAura.skill]: "Skill",
  [LuminanceAura.temperance]: "Temperance",
  [LuminanceAura.valor]: "Valor",
  [LuminanceAura.world]: "World",
  [LuminanceAura.specialization]: "Specialization",
  [LuminanceAura.invulnerability]: "Invulnerability",
  [LuminanceAura.destruction]: "Destruction",
  [LuminanceAura.retribution]: "Retribution",
  [LuminanceAura.hardening]: "Hardening"
};
