-- Create featured_builds table
CREATE TABLE IF NOT EXISTS "public"."featured_builds" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "build_id" "text" NOT NULL
);

ALTER TABLE "public"."featured_builds" OWNER TO "postgres";

-- Auto-increment ID
ALTER TABLE "public"."featured_builds" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."featured_builds_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Primary key
ALTER TABLE ONLY "public"."featured_builds"
    ADD CONSTRAINT "featured_builds_pkey" PRIMARY KEY ("id");

-- Foreign key to builds table
ALTER TABLE ONLY "public"."featured_builds"
    ADD CONSTRAINT "featured_builds_build_id_fkey" FOREIGN KEY ("build_id") REFERENCES "public"."builds"("id") ON DELETE CASCADE;

-- Enable RLS
ALTER TABLE "public"."featured_builds" ENABLE ROW LEVEL SECURITY;

-- RLS policy: everyone can read
CREATE POLICY "Enable read access for all users" ON "public"."featured_builds" FOR SELECT USING (true);

-- Grants
GRANT ALL ON TABLE "public"."featured_builds" TO "anon";
GRANT ALL ON TABLE "public"."featured_builds" TO "authenticated";
GRANT ALL ON TABLE "public"."featured_builds" TO "service_role";

GRANT ALL ON SEQUENCE "public"."featured_builds_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."featured_builds_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."featured_builds_id_seq" TO "service_role";
